# Generated by Django 4.0.3 on 2022-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logon',
            field=models.DateTimeField(null=True),
        ),
    ]
