# Generated by Django 4.0.3 on 2022-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0002_user_last_logon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sd_admin',
            field=models.BooleanField(default=False),
        ),
    ]
