# Generated by Django 4.0.3 on 2022-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0003_user_sd_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_item',
            name='category',
            field=models.CharField(choices=[('', ''), ('Pheripherals', 'Pheripherals'), ('Laptops', 'Laptops'), ('Audio', 'Audio'), ('Mobile devices', 'Mobile devices')], max_length=128),
        ),
        migrations.AlterField(
            model_name='loan_item',
            name='loan_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan_item',
            name='loan_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
