# Generated by Django 4.0.3 on 2022-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0004_alter_loan_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_item',
            name='qr_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
