# Generated by Django 4.0.3 on 2022-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0005_alter_loan_item_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_item',
            name='notes',
            field=models.CharField(default='Note', max_length=256),
        ),
    ]
