# Generated by Django 4.0.3 on 2022-05-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0006_loan_item_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_item',
            name='on_loan',
            field=models.CharField(max_length=3),
        ),
    ]
