# Generated by Django 4.0.3 on 2022-05-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0007_alter_loan_item_on_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='end_user_id',
            new_name='end_user',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_item_id',
            new_name='loan_item',
        ),
    ]
