# Generated by Django 4.0.6 on 2022-07-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0008_rename_end_user_id_loan_end_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sd_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
