# Generated by Django 4.0.6 on 2022-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0009_alter_user_sd_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
