# Generated by Django 4.0.6 on 2022-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0012_alter_loan_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active_loan',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
