# Generated by Django 4.0.6 on 2022-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0013_loan_active_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_end_date',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_start_date',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
