# Generated by Django 4.0.6 on 2022-09-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0014_loan_loan_end_date_loan_loan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_item',
            name='loan_end_date',
        ),
        migrations.RemoveField(
            model_name='loan_item',
            name='loan_start_date',
        ),
    ]
