# Generated by Django 4.0.6 on 2022-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0015_remove_loan_item_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_accepted',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
