# Generated by Django 4.0.6 on 2022-09-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0016_loan_loan_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='end_user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_accepted',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_end_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_item',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_start_date',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_number', models.CharField(max_length=128)),
                ('req_start_date', models.CharField(max_length=128, null=True)),
                ('req_end_date', models.CharField(max_length=128, null=True)),
                ('req_approved', models.CharField(default='No', max_length=3)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_id', to=settings.AUTH_USER_MODEL)),
                ('req_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='loan_equipment_manager.loan_item')),
            ],
        ),
    ]
