# Generated by Django 4.0.6 on 2022-09-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0017_remove_loan_end_user_remove_loan_loan_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='req_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_id', to='loan_equipment_manager.request'),
            preserve_default=False,
        ),
    ]
