# Generated by Django 4.0.6 on 2022-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0018_loan_req_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_approved',
            field=models.CharField(default='Pending', max_length=3),
        ),
    ]
