# Generated by Django 4.0.6 on 2022-09-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0020_loan_end_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_end_date',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_ID', to='loan_equipment_manager.loan_item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_start_date',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
