# Generated by Django 4.0.6 on 2022-09-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0021_loan_loan_end_date_loan_loan_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_end_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_start_date',
        ),
    ]
