# Generated by Django 4.0.6 on 2022-09-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0022_remove_loan_loan_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_item',
        ),
    ]
