# Generated by Django 4.0.6 on 2022-09-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_equipment_manager', '0023_remove_loan_loan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ln_item_id', to='loan_equipment_manager.loan_item'),
            preserve_default=False,
        ),
    ]
